---
title: "webscraping"
author: "Quilvio Hernandez"
date: "6/21/2020"
output: html_document
---

```{r}
library(xml2)
library(rvest)
library(tidyverse)
```

```{r}
url = "https://en.wikipedia.org/wiki/Major_League_Baseball_Most_Valuable_Player_Award"
```

```{r}
url_contents = read_html(url) # Get HTML of page 
url_contents
```

```{r}
mvp_table_html <- html_node(url_contents, xpath ="//*[@id='mw-content-text']/div/table[4]")
mvp_table_df <- html_table(mvp_table_html) # get table of html table
View(mvp_table_df)
```

```{r}
mvp_table_df$`American League winner` <- gsub("[†§^()0-9]+", "", mvp_table_df$`American League winner`)
mvp_table_df$`National League winner` <- gsub("[†§^()0-9]+", "", mvp_table_df$`National League winner`)



tail(mvp_table_df$`American League winner`)
```

```{r}
mvp_table_df$'American League winner' <- trimws(mvp_table_df$`American League winner`, 
                                                which = "both", whitespace = "[ \t\r\n]")
mvp_table_df$'National League winner' <- trimws(mvp_table_df$`National League winner`, 
                                                which = "both", whitespace = "[ \t\r\n]")
```

```{r}
al_mvps <- mvp_table_df[,c(1:4)]
nl_mvps <- mvp_table_df[,c(1,5:7)]

head(al_mvps)
head(nl_mvps)
```


```{r}
url = "https://www.fangraphs.com/leaders.aspx?pos=all&stats=bat&lg=all&qual=y&type=8&season=2019&month=0&season1=2019&ind=0"

url_contents = read_html(url) # Get HTML of page 
url_contents
```

```{r}
hitting_table_html = html_node(url_contents, xpath ='//*[@id="LeaderBoard1_dg1_ctl00"]')
hitting_table = html_table(hitting_table_html) # get table of html table
View(hitting_table)
```





```{r}
headers <- hitting_table[2,]
headers
```
```{r}
names(hitting_table) <- headers
names(hitting_table)
```

```{r}
hitting_table <- hitting_table[-c(1:3),]
head(hitting_table)
```

```{r}
hitting_table$Year <- 2019
```



```{r}
x = 1931:2018
x
```

```{r}
for (year in x) {
  url = paste0("https://www.fangraphs.com/leaders.aspx?pos=all&stats=bat&lg=all&qual=y&type=8&season=",
               year,"&month=0&season1=",
               year,"&ind=0&team=&rost=&age=&filter=&players=&startdate=&enddate=")
  url_contents = read_html(url)
  
  hitting_table_html = html_node(url_contents, xpath ='//*[@id="LeaderBoard1_dg1_ctl00"]')
  to_add = html_table(hitting_table_html)
  
  to_add <- to_add[-c(1:3),]
  names(to_add) <- headers
  to_add$Year <- year
 
  hitting_table <- rbind(hitting_table, to_add) 
}
```




```{r}
hitting_table[, c(1, 4:9, 12:22)] <- sapply(hitting_table[, c(1, 4:9, 12:22)], as.numeric)
hitting_table %>% 
  glimpse()
```

```{r}
hitting_table %>% 
  filter(HR > 35, AVG > .280)
```

```{r}
nl_mvps %>% 
  filter(Position == "RHP" | Position == "LHP")
```

```{r}
al_mvps %>% 
  filter(Position == "RHP" | Position == "LHP")
```
```{r}
# webscraping 2019 pitcher data
pitcher_url = "https://www.fangraphs.com/leaders.aspx?pos=all&stats=pit&lg=all&qual=y&type=8&season=2019&month=0&season1=2019&ind=0"

pitcher_url_contents = read_html(pitcher_url)
pitcher_url_contents
```
```{r}
pitching_table_html = html_node(pitcher_url_contents, xpath = '//*[@id="LeaderBoard1_dg1_ctl00"]')
pitching_table = html_table(pitching_table_html)
View(pitching_table)
```

```{r}
pitcher_headers = pitching_table[2,]
names(pitching_table) = pitcher_headers

```

```{r}
pitching_table = pitching_table[-c(1:3),]
head(pitching_table)
```
```{r}
pitching_table$Year = 2019
head(pitching_table)
```
```{r}
pitching_table %>%
  filter(W >= 15)
```
```{r}
pitching_table[, c(4:13,17:20)] = sapply(pitching_table[, c(4:13, 17:20)], as.numeric)
pitching_table %>% 
  glimpse()
```
```{r}
pitching_table %>%
  filter(W >= 15, ERA < 3.5)
```

```{r}
nl_mvps$Team <- gsub("[*]+", "", nl_mvps$Team)
al_mvps$Team <- gsub("[*]+", "", al_mvps$Team)
```

```{r}
al_mvps %>% 
  head()
```

```{r}
names(nl_mvps)
names(hitting_table)
```

```{r}
names(hitting_table)
```

```{r}
hitting_table <- hitting_table %>% 
  left_join(nl_mvps, by = c("Name" = "National League winner", "Year"), 
            suffix = c("_hitting", "_mvp")) %>% 
  mutate(NL_MVP = if_else(!is.na(Team_mvp),1,0),
         Position = NULL) 
  
```

```{r}
View(hitting_table)

```

```{r}
head(hitting_table)
 hitting_table <- hitting_table %>% 
   mutate(Team_hitting = NULL)
```

```{r}
hitting_table <- hitting_table %>% 
  left_join(al_mvps, by = c("Name" = "American League winner", "Year"), 
            suffix = c("_hitting", "_mvp")) %>% 
  mutate(AL_MVP = if_else(!is.na(Team),1,0),
         Team = NULL,
         Position = NULL)
```

```{r}
head(hitting_table)
```

```{r}
head(hitting_table)
```

```{r}
dim(hitting_table)
```

```{r}
hitting_table %>% 
  glimpse()

hitting_table[, c(1, 3:22)] <- sapply(hitting_table[, c(1, 3:24)], as.numeric)
hitting_table[, c(22:24)] <- sapply(hitting_table[, c(22:24)], as.factor)

hitting_table %>% 
  glimpse()
```
```{r}
levels(hitting_table$NL_MVP)
```
```{r}
hitting_table <- hitting_table %>% 
  mutate(MVP = if_else((AL_MVP == 1 | NL_MVP == 1),1,0),
         MVP = as.factor(MVP))
```


```{r}
hitting_table %>% 
  ggplot(aes(x = HR, y = AVG, color = MVP)) + 
  geom_point() 
```

```{r}
hitting_table %>% 
  ggplot(aes(x = AVG, color = MVP)) + 
  geom_density() 
```

```{r}
hitting_table %>% 
  ggplot(aes(x = HR, color = MVP)) + 
  geom_density() 
```

```{r}
ggplot(data = filter(hitting_table, AL_MVP == 1), aes(x = Year, y = HR))
```

```{r}
hitting_table %>% 
  filter(MVP == 1) %>% 
  ggplot(aes(x = Year, y = HR)) + 
  geom_line()
```

```{r}
ggplot() +
  geom_line(data = subset(hitting_table, NL_MVP == 1), aes(x = Year, y = HR), 
            color = "red") + 
  geom_line(data = subset(hitting_table, AL_MVP == 1), aes(x = Year, y = HR), 
            color = "blue")
```

```{r}
names(hitting_table)
```


```{r}
hitting_table %>% 
  ggplot(aes(x = WAR, color = MVP)) + 
  geom_density() #significant

hitting_table %>% 
  ggplot(aes(x = ISO, color = MVP)) + 
  geom_density() #meh

hitting_table %>% 
  ggplot(aes(x = AVG, color = MVP)) + 
  geom_density() #meh

hitting_table %>% 
  ggplot(aes(x = R, color = MVP)) + 
  geom_density() #useful

hitting_table %>% 
  ggplot(aes(x = RBI, color = MVP)) + 
  geom_density() #useful

hitting_table %>% 
  ggplot(aes(x = HR, color = MVP)) + 
  geom_density() #useful

hitting_table %>% 
  ggplot(aes(x = G, color = MVP)) + 
  geom_density() #useless

hitting_table %>% 
  ggplot(aes(x = wOBA, color = MVP)) + 
  geom_density() #meh

hitting_table %>% 
  ggplot(aes(x = OBP, color = MVP)) + 
  geom_density() #mild

hitting_table %>% 
  ggplot(aes(x = `wRC+`, color = MVP)) + 
  geom_density() #keep

hitting_table %>% 
  ggplot(aes(x = BsR, color = MVP)) + 
  geom_density()  #USELESS 

hitting_table %>% 
  ggplot(aes(x = SB, color = MVP)) + 
  geom_density()  #no diff

hitting_table %>% 
  ggplot(aes(x = BABIP, color = MVP)) + 
  geom_density()  #no diff

hitting_table %>% 
  ggplot(aes(x = Off, color = MVP)) + 
  geom_density()  #no diff

hitting_table %>% 
  ggplot(aes(x = Def, color = MVP)) + 
  geom_density()  #no diff
```

```{r}
hitting_table %>% 
  filter(MVP == 1) %>% 
  summarise(min = min(WAR), 
            max = max(WAR))

hitting_table %>% 
  filter(WAR == 3.9 & MVP == 1)
```

```{r}
hitting_table <- hitting_table %>% 
  group_by(Year) %>% 
  mutate(rank_HR = min_rank(-HR),
         rank_R = min_rank(-R),
         rank_SB = min_rank(-SB),
         rank_ISO = min_rank(-ISO),
         rank_BABIP = min_rank(-BABIP),
         rank_AVG = min_rank(-AVG),
         rank_OBP = min_rank(-OBP),
         rank_SLG = min_rank(-SLG),
         rank_wOBA = min_rank(-wOBA),
         `rank_wRC+` = min_rank(-`wRC+`),
         rank_BsR = min_rank(-BsR),
         rank_Off = min_rank(-Off),
         rank_WAR = min_rank(-WAR)
         ) 
```


```{r}
hitting_table %>% 
  group_by(MVP) %>% 
  summarise(avg_HR_rank = mean(rank_HR),
            avg_R_rank = mean(rank_R),
            rank_SB = mean(rank_SB),
           rank_ISO = mean(rank_ISO),
           rank_BABIP = mean(rank_BABIP),
           rank_AVG = mean(rank_AVG),
           rank_OBP = mean(rank_OBP),
           rank_SLG = mean(rank_SLG),
           rank_wOBA = mean(rank_wOBA),
           `rank_wRC+` = mean(`rank_wRC+`),
           rank_BsR = mean(rank_BsR),
           rank_Off = mean(rank_Off),
           rank_WAR = mean(rank_WAR)
  )
```

```{r}
hitting_table %>% 
  ggplot(aes(x = HR, color = MVP)) + 
  geom_boxplot() +
  coord_flip()

hitting_table %>% 
  ggplot(aes(x = WAR, color = MVP)) + 
  geom_boxplot() +
  coord_flip()

hitting_table %>% 
  ggplot(aes(x = Off, color = MVP)) + 
  geom_boxplot() +
  coord_flip()

hitting_table %>% 
  ggplot(aes(x = `wRC+`, color = MVP)) + 
  geom_boxplot() +
  coord_flip()

hitting_table %>% 
  ggplot(aes(x = wOBA, color = MVP)) + 
  geom_boxplot() +
  coord_flip()
```

```{r}
library(corrplot)
library(corrgram)
library(RColorBrewer)

M <- round(cor(hitting_table[-c(1, 2, 9, 10, 21:36)]), 2)
corrplot(M, type = "upper", method = "color",
         col=brewer.pal(n=8, name="PuOr"))
```

```{r}
library(caret)
library(AppliedPredictiveModeling)
```

```{r}
nzv <- nearZeroVar(hitting_table, saveMetrics= TRUE)
nzv[nzv$nzv,][1:3,]
```

```{r}
nzv <- nearZeroVar(hitting_table)
nzv
```


```{r}
descrCor <- cor(hitting_table[-c(1, 2, 9, 10, 21:38)])
corrplot(descrCor, type = "upper", method = "color",
         col=brewer.pal(n=8, name="PuOr"))
summary(descrCor[upper.tri(descrCor)])
highlyCorDescr <- findCorrelation(descrCor, cutoff = .9)
highlyCorDescr
filteredDescr <- descrCor[,-highlyCorDescr]
descrCor2 <- cor(filteredDescr)
descrCor2
corrplot(descrCor2, type = "upper", method = "color",
         col=brewer.pal(n=8, name="PuOr"))
# filteredDescr <- filteredDescr[,-highlyCorDescr]
# descrCor2 <- cor(filteredDescr)
# summary(descrCor2[upper.tri(descrCor2)])
```

```{r}
table(hitting_table$MVP)
```


```{r}
set.seed(0712)
hitting_table$MVP <- as.factor(hitting_table$MVP)
test <- hitting_table %>% group_by(MVP) %>% sample_frac(.3)
train <- setdiff(hitting_table, test)
dim(test)
dim(train)
```

```{r}
table(test$MVP)
table(train$MVP)
```

```{r}
train[, -c(9, 10,22:24, 26:38)]
names(train)
```


```{r}
down_train <- downSample(x = train[, -c(9, 10,22:38)],
                         y = train$MVP)
dim(down_train)
table(down_train$Class)
down_train
```

```{r}
up_train <- upSample(x = train[, -c(9, 10,22:38)],
                     y = train$MVP)                         
dim(up_train)
table(up_train$Class)
up_train
```

```{r}
library(DMwR)

set.seed(9560)
smote_train <- SMOTE(MVP ~ ., data  = as.data.frame(train[, -c(1, 2,9, 10,17, 22:24, 26:38)]))
table(smote_train$MVP) 
```

```{r}
set.seed(9560)
rose_train <- ROSE(MVP ~ G+PA+HR+R+RBI+SB+ISO+BABIP+AVG+
                     OBP+SLG+wOBA+BsR+Off+Def+WAR, data  = train[, -c(2,9, 10,22:24, 26:38)])$data                    
table(rose_train$MVP)
```

```{r}
ROSE(MVP ~ G+PA+HR+R+RBI+SB+ISO+BABIP+AVG+OBP+SLG+wOBA, data  = train[, -c(2,9, 10,22:24, 26:38)])

```

```{r}
y <- train$MVP
x <- train[-c(1,2,9, 10, 22:39)]
```

```{r}
fitControl <- trainControl(method = "repeatedcv",
                           number = 10,
                           repeats = 10)

set.seed(825)
rfFit <- train(MVP ~ ., data = train[-c(1,2,9, 10, 22:25, 27:39)], 
                 method = "rf", 
                 trControl = fitControl,
                 verbose = FALSE)
rfFit
```

```{r}
x <- predict(rfFit, newdata = test[-c(1,2,9, 10, 22:25, 27:39)], type = "prob")
```

```{r}
test$mvpodds <- x$`1`
```

```{r}
test %>% 
  slice_max(order_by = mvpodds,
            n = 10)
```

```{r}
median(test$mvpodds)
```

